apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: result 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result 
    spec:
      containers:
        - name: result 
          image: admin16acr.azurecr.io/result
          ports:
          - containerPort: 8080